In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
plt.rcParams['font.family'] = 'AppleGothic'

In [3]:
df = pd.read_excel('seoul_csv_gu_list.xlsx')

In [4]:
df_cu = df.ix[:24]

In [5]:
df_gs = df.ix[25:49]

In [6]:
df_seven = df.ix[50:74]

In [7]:
df_mini = df.ix[75:100]

In [8]:
df_cu_i = df_cu.set_index('gu')
df_gs_i = df_gs.set_index('gu')
df_seven_i = df_seven.set_index('gu')
df_mini_i = df_mini.set_index('gu')

In [9]:
df1 = df_cu_i + df_gs_i + df_seven_i + df_mini_i

In [10]:
del(df1['store'])

In [11]:
df1

      number
gu
강남구      627
강동구      227
강북구      164
강서구      257
관악구      289
광진구      233
구로구      213
금천구      156
노원구      220
도봉구      141
동대문구     198
동작구      211
마포구      342
서대문구     192
서초구      336
성동구      153
성북구      226
송파구      330
양천구      169
영등포구     293
용산구      175
은평구      209
종로구      231
중구       253
중랑구      161

In [12]:
df_gs_i.head()

    store  number
gu
강남구  gs25     225
강동구  gs26      87
강북구  gs27      52
강서구  gs28      87
관악구  gs29     114

In [13]:
df_crime = pd.read_excel('crime_gu.xlsx')

In [14]:
df_crime = df_crime.set_index('gu')

In [15]:
df_crime

      crime_num
gu
강남구        7555
관악구        5554
송파구        5356
영등포구       5221
광진구        4566
강서구        4440
구로구        4341
강동구        4261
마포구        4171
노원구        4028
은평구        4016
중구         3982
서초구        3921
종로구        3873
중랑구        3838
동대문구       3805
성북구        3546
양천구        3538
동작구        3309
서대문구       3208
강북구        3071
용산구        3017
금천구        2954
도봉구        2557
성동구        2454

In [16]:
df_result = pd.concat([df1, df_crime])

In [17]:
df_crime = df_crime.sort_index()

In [18]:
df_result = df_crime

In [19]:
df_result['csv_num'] = df1.number

In [20]:
df_result

      crime_num  csv_num
gu
강남구        7555      627
강동구        4261      227
강북구        3071      164
강서구        4440      257
관악구        5554      289
광진구        4566      233
구로구        4341      213
금천구        2954      156
노원구        4028      220
도봉구        2557      141
동대문구       3805      198
동작구        3309      211
마포구        4171      342
서대문구       3208      192
서초구        3921      336
성동구        2454      153
성북구        3546      226
송파구        5356      330
양천구        3538      169
영등포구       5221      293
용산구        3017      175
은평구        4016      209
종로구        3873      231
중구         3982      253
중랑구        3838      161

In [21]:
x = df_result.csv_num
y = df_result.crime_num

In [22]:
x

gu
강남구     627
강동구     227
강북구     164
강서구     257
관악구     289
광진구     233
구로구     213
금천구     156
노원구     220
도봉구     141
동대문구    198
동작구     211
마포구     342
서대문구    192
서초구     336
성동구     153
성북구     226
송파구     330
양천구     169
영등포구    293
용산구     175
은평구     209
종로구     231
중구      253
중랑구     161
Name: csv_num, dtype: int64

In [23]:
df_result.head()

     crime_num  csv_num
gu
강남구       7555      627
강동구       4261      227
강북구       3071      164
강서구       4440      257
관악구       5554      289

In [24]:
df_result['ratio'] = df_result['csv_num'] / df_result['crime_num']

In [25]:
df_result

      crime_num  csv_num     ratio
gu
강남구        7555      627  0.082991
강동구        4261      227  0.053274
강북구        3071      164  0.053403
강서구        4440      257  0.057883
관악구        5554      289  0.052035
광진구        4566      233  0.051029
구로구        4341      213  0.049067
금천구        2954      156  0.052810
노원구        4028      220  0.054618
도봉구        2557      141  0.055143
동대문구       3805      198  0.052037
동작구        3309      211  0.063765
마포구        4171      342  0.081995
서대문구       3208      192  0.059850
서초구        3921      336  0.085692
성동구        2454      153  0.062347
성북구        3546      226  0.063734
송파구        5356      330  0.061613
양천구        3538      169  0.047767
영등포구       5221      293  0.056120
용산구        3017      175  0.058005
은평구        4016      209  0.052042
종로구        3873      231  0.059644
중구         3982      253  0.063536
중랑구        3838      161  0.041949

In [26]:
df_result['ratio'] = df_result['ratio']*100

In [27]:
df_result

      crime_num  csv_num     ratio
gu
강남구        7555      627  8.299140
강동구        4261      227  5.327388
강북구        3071      164  5.340280
강서구        4440      257  5.788288
관악구        5554      289  5.203457
광진구        4566      233  5.102935
구로구        4341      213  4.906704
금천구        2954      156  5.280975
노원구        4028      220  5.461768
도봉구        2557      141  5.514275
동대문구       3805      198  5.203679
동작구        3309      211  6.376549
마포구        4171      342  8.199473
서대문구       3208      192  5.985037
서초구        3921      336  8.569243
성동구        2454      153  6.234719
성북구        3546      226  6.373378
송파구        5356      330  6.161314
양천구        3538      169  4.776710
영등포구       5221      293  5.611952
용산구        3017      175  5.800464
은평구        4016      209  5.204183
종로구        3873      231  5.964369
중구         3982      253  6.353591
중랑구        3838      161  4.194893

In [28]:
df_final = df_result['ratio']
df_final.head()

gu
강남구    8.299140
강동구    5.327388
강북구    5.340280
강서구    5.788288
관악구    5.203457
Name: ratio, dtype: float64

In [29]:
fig = plt.figure(num=None, figsize=(12, 12), dpi=100, facecolor='w', edgecolor='g')

In [30]:
# plt.rcParams.update({'font.size': 16})
# plt.title('2015년 서울시 crime per cvs store 구별')
# plt.ylabel('gu_name')
# plt.xlabel('crime per cvs store')


# df_final.plot(kind='barh', color='g', alpha=0.5)
# plt.savefig('crime_per_csv.png', dpi=500, box_inches='tight')

In [34]:
plt.rcParams.update({'font.size': 12})
plt.title('2015년 서울시 crime 수 구별')
plt.ylabel('gu_name')
plt.xlabel('crime number')

df_crime['crime_num'].plot(kind='barh', color='y', alpha=0.5)

plt.savefig('crime_num.png', dpi=500, box_inches='tight')